lib/desejo_puro_web/router.ex
defmodule DesejoPuroWeb.Router do
  use DesejoPuroWeb, :router

  pipeline :auth do
    plug(DesejoPuro.Auth.Pipeline)
  end

  pipeline :ensure_auth do
    plug(Guardian.Plug.EnsureAuthenticated)
  end

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", DesejoPuroWeb do
    # Use the default browser stack
    pipe_through([:browser, :auth])

    get("/", PageController, :index)
    get("/pilares", PageController, :pilares)

    get("/signout", AuthController, :signout)
    get("/signin", UserController, :new)

    get("/login", AuthController, :login)
    post("/login", AuthController, :login_action)

    scope "/bo" do
      resources("/pilares", PilarController)
      resources("/licoes", LicaoController)

      resources("/users", UserController)
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", DesejoPuroWeb do
  #   pipe_through :api
  # end
end

lib/desejo_puro_web/views/layout_view.ex
defmodule DesejoPuroWeb.LayoutView do
  use DesejoPuroWeb, :view
end

lib/desejo_puro_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>OBPC - Desejo Puro</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Desejo Puro
        </a>
        <ul class="right">
          <%= if Guardian.Plug.current_resource(@conn) do %>
            <li>
              <%= link "Pilares", to: page_path(@conn, :pilares) %>
            </li>
            <li>
              <%= link "Sair", to: auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Entrar", to: auth_path(@conn, :login) %>
            </li>
                        <li>
              <%= link "Cadastrar", to: user_path(@conn, :new) %>
            </li>
          <% end %>
       </ul>
      </div>
    </nav>

    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>